version: 2
updates:

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    groups:
      minor-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
