/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonMatrix: typeof import('./src/components/ButtonMatrix.vue')['default']
    DrawableMatrix: typeof import('./src/components/DrawableMatrix.vue')['default']
    DrawingTransfer: typeof import('./src/components/DrawingTransfer.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    ListComponent: typeof import('./src/components/ListComponent.vue')['default']
    ListComponentButton: typeof import('./src/components/ListComponentButton.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NFlex: typeof import('naive-ui')['NFlex']
    NGi: typeof import('naive-ui')['NGi']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputGroupLabel: typeof import('naive-ui')['NInputGroupLabel']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NSelect: typeof import('naive-ui')['NSelect']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NThemeEditor: typeof import('naive-ui')['NThemeEditor']
    SavedMessages: typeof import('./src/components/SavedMessages.vue')['default']
    TextTransfer: typeof import('./src/components/TextTransfer.vue')['default']
    TogglablePixel: typeof import('./src/components/TogglablePixel.vue')['default']
  }
}
